version: '2'
services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins2
    restart: always
    ports:
      - 8080:8888
      - 50000:50000
    volumes:
      - jenkins2Volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - cicd


  nexus:
    hostname: nexus
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - nexusVolume:/nexus-data sonatype/nexus3
    networks:
      - cicd


networks:
  cicd:
    driver: bridge

volumes:
  #jira2Volume:
  #jira2InstallVolume:
  #confluenceVolume:
  #confluenceInstallVolume:
  #bitbucketVolume:
  #bitbucketInstallVolume:
  #sonarConfVolume:
  #sonarDataVolume:
  #sonarExtensionsVolume:
  jenkins2Volume:
  nexusVolume: